app/Helpers/ResponseBuilder.php
app/Helpers/ResponseInterface.php
app/Http/Controllers/NamespaceController.php
app/Providers/ResponseServiceProvider.php
bootstrap/app.php

A Common response service provider, to build the JSON response.
- Implemented on NameSpaceController.

Create Response Service Provider

---

tests/PasswordApiTest.php
tests/UpdateProfileApiTest.php

@akuks  please review and merge

test cases debugging and fixing

---

app/Http/Controllers/ProfileController.php
bootstrap/app.php
config/message.php

- Add custom message configuration file
- Refactor profileController function changePassword and updateProfile
- Change Swaggerdocumentation

Code refactoring and add Custom message configuration file

---

app/Http/Controllers/NicknameController.php
routes/web.php
tests/NickNameApiTest.php

@akuks please review and merge

Nickname test cases can-82

---

app/Http/Controllers/NicknameController.php
app/Http/Requests/AddNickNameRequest.php
app/Http/Requests/UpdateNickNameRequest.php
app/Models/ExceptionRes.php
app/Models/Nickname.php
bootstrap/app.php
composer.json
config/message.php
routes/web.php
tests/NickNameApiTest.php

@akuks  please review and merge

can-79,80,81

---

.env.example
app/Http/Controllers/ForgotPasswordController.php
app/Http/Controllers/UserController.php
config/message.php

Can-1-iffort-fixed-issue

---

.env.example
app/Http/Controllers/UserController.php
app/Http/Request/ValidationMessages.php
app/Http/Request/ValidationRules.php
app/Models/Country.php
database/data/country.json
database/seeders/CountrySeeder.php
routes/web.php

Setup :
php artisan db:seed --class=CountrySeeder

Can 1 iffort fixed issue

---

routes/web.php

underscores are replaced with hyphens in API endpoints

underscores are replaced with hyphens in API endpoints

---

app/Http/Controllers/AdsController.php
app/Http/Controllers/AlgorithmController.php
app/Http/Controllers/ImageController.php
app/Http/Controllers/NamespaceController.php
app/Http/Controllers/NicknameController.php
app/Http/Controllers/ProfileController.php
app/Http/Controllers/SocialMediaLinkController.php
app/Http/Controllers/VideoPodcastController.php
app/Http/Resources/SuccessResource.php
resources/lang/en/message.php

config() changed to trans() and replaced hard coded messages with trans() from all over the project. 
Added 1 new success message for otp sent in lang/en/message which was previously hard coded.

config() changed to trans() and replaced hard coded messages with trans()

---

tests/NickNameApiTest.php

This PR fixes the NicknameAPITestCase.
@akuks  please review and merge.

tg-nickname-test-case-fix

---

app/Http/Controllers/CampController.php
app/Http/Controllers/StatementController.php
app/Models/Camp.php
resources/lang/en/message.php
tests/GetCampRecordApiTest.php
tests/GetCampStatementApiTest.php
tests/GetTopicRecordApiTest.php

can 337 inside can-189. Updated camp-statement api and cam-record api and all relevant test cases.

Updated camp-statement api and camp-record api

---

database/data/news_feed_file.sql
database/data/statement_file.sql
database/migrations/2022_04_01_110958_create_statement_table.php
database/migrations/2022_04_01_111120_create_news_feed_table.php
tests/EditNewsFeedApiTest.php
tests/GetCampStatementApiTest.php
tests/GetNewsFeedApiTest.php
tests/UpdateNewsFeedApiTest.php

Executed relevant test cases successfully.
Tested by creating and updating records.
Tested migrations up and down functions.

migrations for news_feed and statement tables

---

app/Events/CampForumPostMailEvent.php
app/Helpers/CampForum.php
app/Http/Controllers/ForgotPasswordController.php
app/Http/Controllers/ReplyController.php
app/Http/Controllers/ThreadsController.php
app/Http/Controllers/UserController.php
app/Http/Request/ValidationMessages.php
app/Http/Request/ValidationRules.php
app/Listeners/CampForumPostMailListener.php
app/Mail/CampForumPostMail.php
app/Models/Reply.php
app/Providers/EventServiceProvider.php
database/factories/ReplyFactory.php
database/migrations/2022_04_22_081658_create_thread_table.php
database/migrations/2022_04_22_082115_create_post_table.php
database/migrations/2022_04_22_083502_alter_post_table.php
database/migrations/2022_04_22_084252_add_is_delete_column_in_post_table.php
resources/lang/en/message.php
resources/views/emails/CampForumPostMail.blade.php
routes/web.php
tests/PostApiTest.php

Iffort fixed backlog issue

---

app/Http/Controllers/UploadController.php

This PR fix small bug in fetch uploaded API, found during internal testing.
@akuks  can you please review and merge

tg-bug-fixes

---

resources/lang/en/message.php

This PR fixes validation message issue.
@akuks  please review and merge the PR

tg-can-445

---

app/Helpers/Util.php
app/Http/Controllers/CampController.php
app/Http/Controllers/TopicController.php
app/Http/Request/ValidationRules.php
config/global.php
resources/lang/en/message.php
resources/views/emails/ThankToSubmitterMail.blade.php

Add in ENV File : APP_URL_FRONT_END=https://canonizer3.canonizer.com

Iffort fixed issue : CAN-514,CAN-520,CAN-522,

---

app/Http/Controllers/ProfileController.php

This PR fixes the bug can-547 incorrect OTP message.
@akuks  please review and approve

tg-can- 547

---

app/Helpers/TopicSupport.php
app/Http/Controllers/ProfileController.php
app/Http/Controllers/SupportController.php
database/migrations/2022_05_19_094308_update_supported_camp_procedure_v2.php
routes/web.php

This PR has implementation for **list of supported camps on user profile page: can-525**  
also update camp procedure migration.
@akuks  please review and merge RR

tg-can-525

---

app/Http/Controllers/CampController.php
app/Http/Controllers/NewsFeedController.php
app/Http/Controllers/ThreadsController.php
app/Http/Controllers/TopicController.php
app/Jobs/ActivityLoggerJob.php
app/Models/ActivityLog.php
app/Models/ActivityUser.php
app/Models/User.php

Changed time format and changed user name to nick name in activity logger

changed user name to nick name and change time format

---

app/Http/Controllers/CampController.php
app/Http/Controllers/UserController.php
app/Http/Request/ValidationMessages.php
app/Http/Request/ValidationRules.php
routes/web.php

iffort-fixed-backlog-issue

---

app/Http/Controllers/UploadController.php
resources/lang/en/message.php
resources/views/emails/promotedDelegatesToDirectMail.blade.php

This PR has fixed can-608 and added a email file.
@akuks  please review and merge

tg-can-608

---

app/Helpers/TopicSupport.php
app/Http/Controllers/SupportController.php
app/Models/Camp.php
app/Models/Support.php
resources/lang/en/message.php
routes/web.php

This PR has implementation for API can-693 and can-694
@akuks  please review and merge PR.

tg-can-693

---

app/Helpers/PushNotification.php
app/Helpers/TopicSupport.php
app/Http/Controllers/SupportController.php
resources/lang/en/message.php

This PR has API for **remove delegate support with promoted delegates checks.**
Also sending push notification to promoted delegates.
@akuks  please review and merge PR.

tg-can-945

---

app/Models/Nickname.php

This PR has fixes for can-1001 
@akuks  please review and merge PR

tg-can-1001

---

app/Helpers/PushNotification.php
app/Helpers/TopicSupport.php
app/Http/Controllers/CampController.php
app/Http/Controllers/NotificationController.php
app/Http/Controllers/ReplyController.php
app/Http/Controllers/StatementController.php
app/Http/Controllers/SupportController.php
app/Http/Controllers/ThreadsController.php
app/Http/Request/ValidationMessages.php
app/Http/Request/ValidationRules.php
app/Models/Camp.php
database/migrations/2022_08_02_093050_add_fcm_token_person_table.php
resources/lang/en/message.php
routes/web.php

1. Changes in Push Notification 
2. Create New API for update fcm token.
Setp:
Run Migration

Can 729 iffort

---

app/Helpers/TopicSupport.php
app/Models/Camp.php
resources/lang/en/message.php

This PR has minor fix required from API end, rest will be fixed from fron-end.
@akuks  please review and merge PR

tg-can-668

---

app/Helpers/Util.php
app/Http/Controllers/CampController.php
app/Http/Controllers/TopicController.php
app/Jobs/CanonizerService.php
app/Models/Camp.php
app/Models/Topic.php
database/migrations/2022_08_16_062309_add_field_in_topic_table.php
database/migrations/2022_08_16_062335_add_field_in_camp_table.php

Can 918 iffort

---

app/Models/Search.php

Format the query with conditions and results.

Query changes related to historical data search

---

app/Console/Commands/AddExsistingDataToElasticSearch.php
app/Helpers/ElasticSearch.php
app/Http/Controllers/SearchController.php
app/Models/Camp.php
app/Models/Nickname.php
app/Models/Search.php
app/Models/Statement.php
app/Models/Topic.php
database/data/modified_existing_data_to_elasticsearch.sql
database/migrations/2025_02_07_095501_sp_update_elasticsearch_table.php
routes/web.php

1. Run command for elasticsearch import.
**Command: php artisan elasticsearch:import**
2. Run the migration command for new SP changes.
3. Require to check the version of Elasticsearch

Talentelgia api 1689

---

database/data/user_support_optimized_new.sql
database/migrations/2025_02_14_083118_alter_sp_user_support_add_grpconcat_len.php

Please run the migrations. I have updated the stored proceedure of user support.

Fix delegate camps

---

app/Console/Commands/AddExsistingDataToElasticSearch.php
app/Models/Search.php
database/data/modified_existing_data_to_elasticsearch.sql
database/migrations/2025_02_17_065146_alter_elasticsearch_sp_with_commandline.php

Please run the migrations and the command.
php artisan elasticsearch:import

Modified SP and command for ElasticSearch data

---

app/Http/Controllers/ActivityController.php
app/Http/Controllers/AlgorithmController.php
app/Http/Controllers/MetaTagController.php
app/Http/Controllers/ReplyController.php
app/Http/Controllers/SearchController.php
app/Swagger/OpenApiSpec.php
app/Swagger/Schemas.php
composer.json

Please run the **composer update** command as new packages are installed for swagger annotations.
After that **generate the swagger documentation** using command:
**vendor/bin/openapi --output public/canonizer_api.json app/Http/Controllers/**
It will be accessible by **[APP_URL/canonizer_api.html]**

Itr11 api 1324

---

app/Http/Controllers/ActivityController.php
app/Http/Controllers/AlgorithmController.php
app/Http/Controllers/SocialMediaLinkController.php
app/Http/Controllers/TermAndServicesController.php

app/Http/Controllers/SocialMediaLinkController.php [Completed]
app/Http/Controllers/TermAndServicesController.php [Completed]
app/Http/Controllers/AlgorithmController.php [Completed]
app/Http/Controllers/AdController.php [Completed]

Fixed and verified the annotations

---

app/Console/Commands/UpdateGravatar.php
app/Console/Kernel.php
app/Http/Controllers/UserController.php

@akuks , Please run the command to update the gravatar images of exising users. This command will update only those users whose profile_picture_path is empty.
**php artisan update-gravatar**

Added gravatar logic and command to update the gravatars
